server :
    port : 8181

#DB configuration

spring: 
    application:
        name: movie-service
    datasource:
        name: dsource
        url: jdbc:mysql://localhost:3306/SMART_CONTACT
        username: root
        password: P@ssmysql
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        properties:
            hibernate: 
                dilect: org.hibernate.dialect.MySQL55Dialect.MySQL55Dialect√é
                use-new-id-generator-mappings: false
        hibernate:
            ddl-auto: update